# Bind NVIDIA GPU & Audio to vfio-pci
options vfio-pci ids=10de:1f99,10de:10fa

# Force vfio-pci to load before NVIDIA drivers
softdep nvidia pre: vfio-pci
softdep nvidia-gpu pre: vfio-pci
softdep nvidia-modeset pre: vfio-pci
softdep nvidia-drm pre: vfio-pci
softdep nouveau pre: vfio-pci
